---
language: ruby
before_install: rm Gemfile.lock || true
sudo: false
cache: bundler
script: bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 4.0" CHECK=test PARALLEL_TEST_PROCESSORS=12
  - rvm: 2.4.3
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.0
    bundler_args: --without system_tests development release
    env: PUPPET_VERSION="~> 5.0" CHECK=test
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=debian8-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=debian9-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=ubuntu1404-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
  - rvm: 2.5.1
    bundler_args: --without development release
    dist: trusty
    env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_setfile=ubuntu1604-64{hypervisor=docker} CHECK=beaker
    services: docker
    sudo: required
